# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VRPUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 856)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(600, 600))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(600, 600))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Custumer_Button = QtWidgets.QPushButton(self.groupBox_4)
        self.Custumer_Button.setObjectName("Custumer_Button")
        self.verticalLayout_3.addWidget(self.Custumer_Button)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.spinBox_Number = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_Number.setMinimum(1)
        self.spinBox_Number.setMaximum(999)
        self.spinBox_Number.setObjectName("spinBox_Number")
        self.verticalLayout_4.addWidget(self.spinBox_Number)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.spinBox_X = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinBox_X.setMaximum(99999)
        self.spinBox_X.setObjectName("spinBox_X")
        self.horizontalLayout_7.addWidget(self.spinBox_X)
        self.spinBox_Y = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinBox_Y.setMaximum(99999)
        self.spinBox_Y.setObjectName("spinBox_Y")
        self.horizontalLayout_7.addWidget(self.spinBox_Y)
        self.ChangeLocation_pushButton = QtWidgets.QPushButton(self.groupBox_9)
        self.ChangeLocation_pushButton.setObjectName("ChangeLocation_pushButton")
        self.horizontalLayout_7.addWidget(self.ChangeLocation_pushButton)
        self.verticalLayout_4.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spinBox_Q = QtWidgets.QSpinBox(self.groupBox_10)
        self.spinBox_Q.setMaximum(999)
        self.spinBox_Q.setObjectName("spinBox_Q")
        self.horizontalLayout_6.addWidget(self.spinBox_Q)
        self.ChangeQ_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.ChangeQ_pushButton.setObjectName("ChangeQ_pushButton")
        self.horizontalLayout_6.addWidget(self.ChangeQ_pushButton)
        self.verticalLayout_4.addWidget(self.groupBox_10)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_mannual_point_index = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_mannual_point_index.setMaximum(999)
        self.spinBox_mannual_point_index.setObjectName("spinBox_mannual_point_index")
        self.gridLayout.addWidget(self.spinBox_mannual_point_index, 1, 1, 1, 1)
        self.pushButton_auto_VRP = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_auto_VRP.setObjectName("pushButton_auto_VRP")
        self.gridLayout.addWidget(self.pushButton_auto_VRP, 0, 0, 1, 1)
        self.pushButton_manual_VRP = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_manual_VRP.setObjectName("pushButton_manual_VRP")
        self.gridLayout.addWidget(self.pushButton_manual_VRP, 1, 0, 1, 1)
        self.choose_point_pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.choose_point_pushButton.setObjectName("choose_point_pushButton")
        self.gridLayout.addWidget(self.choose_point_pushButton, 1, 3, 1, 1)
        self.VRPcar_pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.VRPcar_pushButton.setObjectName("VRPcar_pushButton")
        self.gridLayout.addWidget(self.VRPcar_pushButton, 0, 3, 1, 1)
        self.VRPcar_spinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.VRPcar_spinBox.setMinimum(1)
        self.VRPcar_spinBox.setProperty("value", 2)
        self.VRPcar_spinBox.setObjectName("VRPcar_spinBox")
        self.gridLayout.addWidget(self.VRPcar_spinBox, 2, 0, 1, 1)
        self.spinBox_auto_point_num = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBox_auto_point_num.setMinimum(0)
        self.spinBox_auto_point_num.setMaximum(999)
        self.spinBox_auto_point_num.setProperty("value", 0)
        self.spinBox_auto_point_num.setObjectName("spinBox_auto_point_num")
        self.gridLayout.addWidget(self.spinBox_auto_point_num, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ShowTW_Button = QtWidgets.QPushButton(self.groupBox_5)
        self.ShowTW_Button.setObjectName("ShowTW_Button")
        self.horizontalLayout_4.addWidget(self.ShowTW_Button)
        self.TWcar_spinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.TWcar_spinBox.setMinimum(1)
        self.TWcar_spinBox.setObjectName("TWcar_spinBox")
        self.horizontalLayout_4.addWidget(self.TWcar_spinBox)
        self.TWcar_pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.TWcar_pushButton.setObjectName("TWcar_pushButton")
        self.horizontalLayout_4.addWidget(self.TWcar_pushButton)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CVRP_pushButton = QtWidgets.QPushButton(self.groupBox_7)
        self.CVRP_pushButton.setObjectName("CVRP_pushButton")
        self.horizontalLayout_5.addWidget(self.CVRP_pushButton)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_3)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 500, 2500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.labellist = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labellist.setGeometry(QtCore.QRect(0, 0, 500, 10000))
        self.labellist.setMinimumSize(QtCore.QSize(300, 10000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.labellist.setFont(font)
        self.labellist.setText("")
        self.labellist.setWordWrap(True)
        self.labellist.setObjectName("labellist")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        spacerItem = QtWidgets.QSpacerItem(20, 664, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "路径展示"))
        self.Custumer_Button.setText(_translate("MainWindow", "目标点导入"))
        self.groupBox_8.setTitle(_translate("MainWindow", "修改坐标信息"))
        self.spinBox_Number.setPrefix(_translate("MainWindow", "坐标序号："))
        self.spinBox_X.setPrefix(_translate("MainWindow", "X:"))
        self.spinBox_Y.setPrefix(_translate("MainWindow", "Y:"))
        self.ChangeLocation_pushButton.setText(_translate("MainWindow", "修改"))
        self.spinBox_Q.setPrefix(_translate("MainWindow", "Q:"))
        self.ChangeQ_pushButton.setText(_translate("MainWindow", "修改"))
        self.groupBox_6.setTitle(_translate("MainWindow", "VRP"))
        self.spinBox_mannual_point_index.setPrefix(_translate("MainWindow", "点序号："))
        self.pushButton_auto_VRP.setText(_translate("MainWindow", "自动VRP"))
        self.pushButton_manual_VRP.setText(_translate("MainWindow", "手动VRP"))
        self.choose_point_pushButton.setText(_translate("MainWindow", "选点"))
        self.VRPcar_pushButton.setText(_translate("MainWindow", "修改数量"))
        self.VRPcar_spinBox.setPrefix(_translate("MainWindow", "车辆数目："))
        self.spinBox_auto_point_num.setPrefix(_translate("MainWindow", "点数量："))
        self.groupBox_5.setTitle(_translate("MainWindow", "VRP_TW"))
        self.ShowTW_Button.setText(_translate("MainWindow", "路径展示"))
        self.TWcar_spinBox.setPrefix(_translate("MainWindow", "车辆数目:"))
        self.TWcar_pushButton.setText(_translate("MainWindow", "修改"))
        self.groupBox_7.setTitle(_translate("MainWindow", "CVRP"))
        self.CVRP_pushButton.setText(_translate("MainWindow", "路径展示"))
        self.groupBox_3.setTitle(_translate("MainWindow", "信息表"))

